arch:
  - amd64
  - ppc64le
sudo: false
language: node_js
#Added node_js version node
node_js:
  - "lts/*"
  - "node"
  - "9"
  - "10"
matrix:
  include:
    - node_js: "lts/*"
      env: TEST_SUITE=standard
    - node_js: "lts/*"
      arch: ppc64le
      env: TEST_SUITE=standard
env:
  - TEST_SUITE=unit
script: npm run-script $TEST_SUITE
